# -*- coding: utf-8 -*-
"""ejercicio1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pvpGzZomJo89D1Um7XeYXbFHcGKqO5Y5
"""

print("Hello world!")

"""**hola**"""